/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "SweetyHou的博客",
  "description": "学习创建自己的博客（vuepress）",
  "base": "/blogs/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/home.jpg",
        "heroText": "Sweety Hou",
        "heroImageStyle": {
          "maxHeight": "288px",
          "display": "block",
          "borderRadius": "19% 81% 23% 77% / 44% 57% 43% 56%",
          "boxShadow": "0 15px 18px rgba(0,0,0,0.2)"
        }
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-aaa83dfa",
      "path": "/"
    },
    {
      "title": "视频文件放在HTML中播放不成功",
      "frontmatter": {
        "title": "视频文件放在HTML中播放不成功",
        "date": "2023-2-2",
        "categories": [
          "前端"
        ],
        "tags": [
          "工作问题总结"
        ],
        "sticky": 0
      },
      "regularPath": "/blogs/1.html",
      "relativePath": "blogs/1.md",
      "key": "v-48e637cb",
      "path": "/blogs/1.html"
    },
    {
      "title": "2023对自己说的话",
      "frontmatter": {
        "title": "2023对自己说的话",
        "date": "2023-1-30",
        "categories": [
          "随笔"
        ],
        "tags": [
          "mood"
        ],
        "sticky": 0
      },
      "regularPath": "/blogs/2.html",
      "relativePath": "blogs/2.md",
      "key": "v-c976232a",
      "path": "/blogs/2.html",
      "headers": [
        {
          "level": 2,
          "title": "工作",
          "slug": "工作"
        },
        {
          "level": 2,
          "title": "学习",
          "slug": "学习"
        },
        {
          "level": 2,
          "title": "生活",
          "slug": "生活"
        }
      ]
    },
    {
      "title": ".md文档写作规范",
      "frontmatter": {
        "title": ".md文档写作规范",
        "date": "2023-2-2",
        "categories": [
          "前端"
        ],
        "tags": [
          "markdown"
        ],
        "sticky": 1
      },
      "regularPath": "/blogs/3.html",
      "relativePath": "blogs/3.md",
      "key": "v-24b8b5ea",
      "path": "/blogs/3.html",
      "headers": [
        {
          "level": 2,
          "title": "一、标题语法",
          "slug": "一、标题语法"
        },
        {
          "level": 2,
          "title": "二、段落语法",
          "slug": "二、段落语法"
        },
        {
          "level": 2,
          "title": "三、换行语法",
          "slug": "三、换行语法"
        },
        {
          "level": 2,
          "title": "四、强调语法",
          "slug": "四、强调语法"
        },
        {
          "level": 2,
          "title": "五、引用语法",
          "slug": "五、引用语法"
        },
        {
          "level": 2,
          "title": "六、列表语法",
          "slug": "六、列表语法"
        }
      ]
    },
    {
      "title": "前端小知识",
      "frontmatter": {
        "title": "前端小知识",
        "date": "2023-2-2",
        "categories": [
          "前端"
        ],
        "tags": [
          "js"
        ],
        "sticky": 0
      },
      "regularPath": "/blogs/4.study.html",
      "relativePath": "blogs/4.study.md",
      "key": "v-389cea4b",
      "path": "/blogs/4.study.html",
      "headers": [
        {
          "level": 2,
          "title": "数组去重",
          "slug": "数组去重"
        }
      ]
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "工作问题总结 Tags"
      },
      "regularPath": "/tag/%E5%B7%A5%E4%BD%9C%E9%97%AE%E9%A2%98%E6%80%BB%E7%BB%93/",
      "key": "v-9c80e83c",
      "path": "/tag/工作问题总结/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "mood Tags"
      },
      "regularPath": "/tag/mood/",
      "key": "v-142138a4",
      "path": "/tag/mood/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "markdown Tags"
      },
      "regularPath": "/tag/markdown/",
      "key": "v-3ae5b494",
      "path": "/tag/markdown/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "js Tags"
      },
      "regularPath": "/tag/js/",
      "key": "v-e8d86dc8",
      "path": "/tag/js/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "前端 Categories"
      },
      "regularPath": "/categories/%E5%89%8D%E7%AB%AF/",
      "key": "v-14bbbf36",
      "path": "/categories/前端/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "随笔 Categories"
      },
      "regularPath": "/categories/%E9%9A%8F%E7%AC%94/",
      "key": "v-2bf76980",
      "path": "/categories/随笔/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "首页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "博客",
        "items": [
          {
            "text": "掘金",
            "link": "https://juejin.cn/user/233526039432445"
          },
          {
            "text": "Github",
            "link": "https://github.com/Xusssyyy"
          }
        ]
      }
    ],
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "博客"
      },
      "tag": {
        "location": 4,
        "text": "Tag"
      }
    },
    "author": "Sweety Hou",
    "logo": "/OIP-C.jpg",
    "authorAvatar": "/OIP-C.jpg",
    "type": "blog"
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}