/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "SweetyHou的博客",
  "description": "学习创建自己的博客（vuepress）",
  "base": "/blogs/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/home.jpg",
        "heroText": "Sweety Hou",
        "heroImageStyle": {
          "maxHeight": "288px",
          "display": "block",
          "borderRadius": "19% 81% 23% 77% / 44% 57% 43% 56%",
          "boxShadow": "0 15px 18px rgba(0,0,0,0.2)"
        }
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-aaa83dfa",
      "path": "/"
    },
    {
      "title": "手把手教你轻松手写防抖和节流🔥",
      "frontmatter": {
        "title": "手把手教你轻松手写防抖和节流🔥",
        "date": "2023-1-1",
        "categories": [
          "前端"
        ],
        "tags": [
          "JavaScript",
          "手写"
        ],
        "sticky": 1
      },
      "regularPath": "/blogs/1.html",
      "relativePath": "blogs/1.md",
      "key": "v-48e637cb",
      "path": "/blogs/1.html"
    },
    {
      "title": "手把手教你轻松手写防抖和节流🔥",
      "frontmatter": {
        "title": "手把手教你轻松手写防抖和节流🔥",
        "date": "2023-1-1",
        "categories": [
          "前端"
        ],
        "tags": [
          "JavaScript",
          "手写"
        ],
        "sticky": 1
      },
      "regularPath": "/blogs/3.html",
      "relativePath": "blogs/3.md",
      "key": "v-24b8b5ea",
      "path": "/blogs/3.html"
    },
    {
      "title": "2023对自己说的话",
      "frontmatter": {
        "title": "2023对自己说的话",
        "date": "2023-1-1",
        "categories": [
          "随笔"
        ],
        "tags": [
          "想到什么写什么"
        ],
        "sticky": 2
      },
      "regularPath": "/blogs/2.html",
      "relativePath": "blogs/2.md",
      "key": "v-c976232a",
      "path": "/blogs/2.html"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "首页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "博客",
        "items": [
          {
            "text": "掘金",
            "link": "https://juejin.cn/user/233526039432445"
          },
          {
            "text": "Github",
            "link": "https://github.com/Xusssyyy"
          }
        ]
      }
    ],
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "博客"
      },
      "tag": {
        "location": 4,
        "text": "Tag"
      }
    },
    "author": "Sweety Hou",
    "logo": "/OIP-C.jpg",
    "authorAvatar": "/OIP-C.jpg",
    "type": "blog"
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}