/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "JavaScript": {
      "key": "JavaScript",
      "scope": "tags",
      "path": "/tag/JavaScript/",
      "pageKeys": [
        "v-48e637cb",
        "v-24b8b5ea"
      ]
    },
    "手写": {
      "key": "手写",
      "scope": "tags",
      "path": "/tag/手写/",
      "pageKeys": [
        "v-48e637cb",
        "v-24b8b5ea"
      ]
    },
    "想到什么写什么": {
      "key": "想到什么写什么",
      "scope": "tags",
      "path": "/tag/想到什么写什么/",
      "pageKeys": [
        "v-c976232a"
      ]
    }
  },
  "categories": {
    "前端": {
      "key": "前端",
      "scope": "categories",
      "path": "/categories/前端/",
      "pageKeys": [
        "v-48e637cb",
        "v-24b8b5ea"
      ]
    },
    "随笔": {
      "key": "随笔",
      "scope": "categories",
      "path": "/categories/随笔/",
      "pageKeys": [
        "v-c976232a"
      ]
    }
  },
  "timeline": {}
}