/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "工作问题总结": {
      "key": "工作问题总结",
      "scope": "tags",
      "path": "/tag/工作问题总结/",
      "pageKeys": [
        "v-48e637cb"
      ]
    },
    "mood": {
      "key": "mood",
      "scope": "tags",
      "path": "/tag/mood/",
      "pageKeys": [
        "v-c976232a"
      ]
    },
    "markdown": {
      "key": "markdown",
      "scope": "tags",
      "path": "/tag/markdown/",
      "pageKeys": [
        "v-24b8b5ea"
      ]
    },
    "js": {
      "key": "js",
      "scope": "tags",
      "path": "/tag/js/",
      "pageKeys": [
        "v-389cea4b"
      ]
    }
  },
  "categories": {
    "前端": {
      "key": "前端",
      "scope": "categories",
      "path": "/categories/前端/",
      "pageKeys": [
        "v-48e637cb",
        "v-24b8b5ea",
        "v-389cea4b"
      ]
    },
    "随笔": {
      "key": "随笔",
      "scope": "categories",
      "path": "/categories/随笔/",
      "pageKeys": [
        "v-c976232a"
      ]
    }
  },
  "timeline": {}
}