/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "tags",
  id: "mood",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/mood/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "工作问题总结",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/工作问题总结/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "markdown",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/markdown/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "js",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/js/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "算法",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/算法/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "随笔",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/随笔/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "前端",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/前端/","interval":[0,3]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "LeetCode",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/LeetCode/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
}]